Puntjesopdei
kevinvgils/AvansApp pull request #21
Opened 2022-06-08 17:07 UTC by Dimitri-de-bie

Alles van Mohammed, Bryan en mijzelf samen gevoegd. je kan dit testen door naar http://localhost/AvansApp/overzichtgebruiker.php te gaan, hier kies je een route en klik je op start. wanneer je op start hebt geklikt maak je een team aan en start je de route nogmaals. je komt hier dan uit op de map. eenmaal op map zie je (mischien punten vanwege dat alleen de eerste route punten heeft), ook zie je rechts boven een knopje wanneer je hier op klikt word je doorgestuurd naar het overzicht van de vragen. hier kan je op de vragen klikken voor de details(echter niet de locatie vragen vanwege dat je dat alleen op locatie zou moeten kunnen doen). ook zie je rechtboven een knop om terug naar de map te gaan.

2022-06-08 17:16 UTC, BBosgraaf approved these changes
LGTM!

2022-06-08 17:19 UTC, BBosgraaf submitted a review, later dismissed
LGTM!

2022-06-08 18:32 UTC, kevinvgils requested changes
alleen deze 3 in dataacces dan is helemaal prima

2022-06-08 18:32 UTC, kevinvgils commented on map.php
> +    $query = "SELECT * FROM `question` WHERE `longitude` IS NOT NULL AND `latitude` IS NOT NULL AND `routeId` =" . $getRouteId;
in dataaccess

2022-06-08 18:32 UTC, kevinvgils commented on questionoverview.php
> +                                            $query = "SELECT * FROM `question` WHERE `questionId` =" . $getQuestionId . "  AND `routeId` = 1";
in dataaccess

2022-06-08 18:32 UTC, kevinvgils commented on questionoverview.php
> +                                                    $queryAnswer = "SELECT * FROM `answer` WHERE questionId =" . $questions->questionId;
in dataaccess

2022-06-08 20:52 UTC, Dimitri-de-bie commented
de Queries zijn toegevoegd aan de dataaccess

2022-06-09 07:55 UTC, kevinvgils approved these changes

2022-06-09 07:57 UTC, N1TROGUE approved these changes

2022-06-09 09:26 UTC, goldo63 approved these changes
LGTM!

2022-06-09 09:32 UTC, merged